export default function IconBotAvatar({ className, ...props }) {
  return (
    <svg className={className} {...props}
                width="28"
                height="28"
                viewBox="0 0 32 32"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                {/* Soma */}
                <circle
                  cx="16"
                  cy="16"
                  r="3.5"
                  fill="#EF4444"
                  stroke="#C2180A"
                  strokeWidth="0.8"
                />
                <circle
                  cx="16"
                  cy="16"
                  r="1.8"
                  fill="white"
                  fillOpacity="0.5"
                />

                {/* Dendrita N (arriba) */}
                <line
                  x1="16"
                  y1="12.5"
                  x2="16"
                  y2="5"
                  stroke="#EF4444"
                  strokeWidth="1.4"
                  strokeLinecap="round"
                />
                <line
                  x1="16"
                  y1="8"
                  x2="13.5"
                  y2="5.5"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
                <line
                  x1="16"
                  y1="6"
                  x2="18"
                  y2="3.5"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
                <line
                  x1="13.5"
                  y1="5.5"
                  x2="12"
                  y2="3.5"
                  stroke="#EF4444"
                  strokeWidth="0.8"
                  strokeLinecap="round"
                />

                {/* Dendrita NE */}
                <line
                  x1="18.5"
                  y1="13.5"
                  x2="25"
                  y2="7"
                  stroke="#EF4444"
                  strokeWidth="1.4"
                  strokeLinecap="round"
                />
                <line
                  x1="23"
                  y1="8.5"
                  x2="26"
                  y2="6"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
                <line
                  x1="25"
                  y1="7"
                  x2="27"
                  y2="9"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />

                {/* Dendrita E (derecha) */}
                <line
                  x1="19.5"
                  y1="16"
                  x2="28"
                  y2="16"
                  stroke="#EF4444"
                  strokeWidth="1.4"
                  strokeLinecap="round"
                />
                <line
                  x1="25"
                  y1="16"
                  x2="28"
                  y2="13.5"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
                <line
                  x1="26"
                  y1="16"
                  x2="28"
                  y2="18.5"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />

                {/* Dendrita SE */}
                <line
                  x1="18.5"
                  y1="18.5"
                  x2="25"
                  y2="25"
                  stroke="#EF4444"
                  strokeWidth="1.4"
                  strokeLinecap="round"
                />
                <line
                  x1="23.5"
                  y1="24"
                  x2="27"
                  y2="25"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
                <line
                  x1="25"
                  y1="25"
                  x2="24"
                  y2="28"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />

                {/* Axón S (abajo) */}
                <line
                  x1="16"
                  y1="19.5"
                  x2="16"
                  y2="28"
                  stroke="#EF4444"
                  strokeWidth="1.4"
                  strokeLinecap="round"
                />
                <line
                  x1="16"
                  y1="25"
                  x2="13.5"
                  y2="28"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
                <line
                  x1="16"
                  y1="26"
                  x2="18.5"
                  y2="29"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />

                {/* Dendrita SW */}
                <line
                  x1="13.5"
                  y1="18.5"
                  x2="7"
                  y2="25"
                  stroke="#EF4444"
                  strokeWidth="1.4"
                  strokeLinecap="round"
                />
                <line
                  x1="8.5"
                  y1="24"
                  x2="5"
                  y2="25"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
                <line
                  x1="7"
                  y1="25"
                  x2="8"
                  y2="28"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />

                {/* Dendrita W (izquierda) */}
                <line
                  x1="12.5"
                  y1="16"
                  x2="4"
                  y2="16"
                  stroke="#EF4444"
                  strokeWidth="1.4"
                  strokeLinecap="round"
                />
                <line
                  x1="6"
                  y1="16"
                  x2="4"
                  y2="13.5"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
                <line
                  x1="5"
                  y1="16"
                  x2="3.5"
                  y2="18.5"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />

                {/* Dendrita NW */}
                <line
                  x1="13.5"
                  y1="13.5"
                  x2="7"
                  y2="7"
                  stroke="#EF4444"
                  strokeWidth="1.4"
                  strokeLinecap="round"
                />
                <line
                  x1="9"
                  y1="8.5"
                  x2="6"
                  y2="6"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
                <line
                  x1="7"
                  y1="7"
                  x2="5"
                  y2="9"
                  stroke="#EF4444"
                  strokeWidth="1"
                  strokeLinecap="round"
                />
              </svg>
  );
}
