export default function IconEgresos({ className, ...props }) {
  return (
    <svg className={`icon-svg ${className || ""}`} {...props}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    {/* recibo */}
                    <rect
                      x="10"
                      y="10"
                      width="34"
                      height="44"
                      rx="3"
                      fill="#8B1A1A"
                      fillOpacity="0.22"
                    />
                    {/* header */}
                    <rect
                      x="10"
                      y="10"
                      width="34"
                      height="10"
                      rx="3"
                      fill="#8B1A1A"
                      fillOpacity="0.5"
                    />
                    <rect
                      x="10"
                      y="16"
                      width="34"
                      height="4"
                      fill="#8B1A1A"
                      fillOpacity="0.5"
                    />
                    {/* líneas detalle */}
                    <rect
                      x="16"
                      y="26"
                      width="20"
                      height="2.5"
                      rx="1.2"
                      fill="#8B1A1A"
                      fillOpacity="0.6"
                    />
                    <rect
                      x="16"
                      y="31"
                      width="14"
                      height="2"
                      rx="1"
                      fill="#8B1A1A"
                      fillOpacity="0.42"
                    />
                    <rect
                      x="16"
                      y="36"
                      width="17"
                      height="2"
                      rx="1"
                      fill="#8B1A1A"
                      fillOpacity="0.42"
                    />
                    <rect
                      x="16"
                      y="41"
                      width="11"
                      height="2"
                      rx="1"
                      fill="#8B1A1A"
                      fillOpacity="0.3"
                    />
                    {/* total */}
                    <rect
                      x="10"
                      y="47"
                      width="34"
                      height="1"
                      rx="0.5"
                      fill="#8B1A1A"
                      fillOpacity="0.4"
                    />
                    <rect
                      x="16"
                      y="49"
                      width="20"
                      height="3"
                      rx="1.5"
                      fill="#8B1A1A"
                      fillOpacity="0.65"
                    />
                    {/* acento: tarjeta de crédito */}
                    {/* cuerpo tarjeta */}
                    <rect
                      x="36"
                      y="38"
                      width="24"
                      height="16"
                      rx="2.5"
                      fill="#FF6B4A"
                      fillOpacity="0.90"
                    />
                    <rect
                      x="36"
                      y="38"
                      width="24"
                      height="16"
                      rx="2.5"
                      fill="none"
                      stroke="#FF6B4A"
                      strokeWidth="0.8"
                      strokeOpacity="0.60"
                    />
                    {/* banda magnética superior */}
                    <rect
                      x="36"
                      y="42"
                      width="24"
                      height="4"
                      fill="#1a0404"
                      fillOpacity="0.35"
                    />
                    {/* chip EMV */}
                    <rect
                      x="39"
                      y="48"
                      width="6"
                      height="4"
                      rx="1"
                      fill="#1a0404"
                      fillOpacity="0.30"
                    />
                    <rect
                      x="39"
                      y="48"
                      width="6"
                      height="4"
                      rx="1"
                      fill="none"
                      stroke="#FF6B4A"
                      strokeWidth="0.5"
                      strokeOpacity="0.50"
                    />
                    <line
                      x1="39"
                      y1="50"
                      x2="45"
                      y2="50"
                      stroke="#FF6B4A"
                      strokeWidth="0.4"
                      strokeOpacity="0.40"
                    />
                    <line
                      x1="42"
                      y1="48"
                      x2="42"
                      y2="52"
                      stroke="#FF6B4A"
                      strokeWidth="0.4"
                      strokeOpacity="0.40"
                    />
                    {/* últimos 4 dígitos */}
                    <rect
                      x="48"
                      y="49"
                      width="3"
                      height="1.5"
                      rx="0.5"
                      fill="#1a0404"
                      fillOpacity="0.35"
                    />
                    <rect
                      x="52"
                      y="49"
                      width="3"
                      height="1.5"
                      rx="0.5"
                      fill="#1a0404"
                      fillOpacity="0.35"
                    />
                    <rect
                      x="56"
                      y="49"
                      width="3"
                      height="1.5"
                      rx="0.5"
                      fill="#1a0404"
                      fillOpacity="0.35"
                    />
                  </svg>
  );
}
