export default function IconResultados({ className, ...props }) {
  return (
    <svg className={`icon-svg ${className || ""}`} {...props}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    {/* card sup izq — barras */}
                    <rect
                      x="4"
                      y="6"
                      width="26"
                      height="24"
                      rx="3"
                      fill="#C0522A"
                      fillOpacity="0.42"
                    />
                    <rect
                      x="4"
                      y="6"
                      width="26"
                      height="6"
                      rx="3"
                      fill="#C0522A"
                      fillOpacity="0.65"
                    />
                    <rect
                      x="4"
                      y="9"
                      width="26"
                      height="3"
                      fill="#C0522A"
                      fillOpacity="0.65"
                    />
                    {/* barras internas */}
                    <rect
                      x="7"
                      y="24"
                      width="4"
                      height="4"
                      rx="1"
                      fill="#C0522A"
                      fillOpacity="0.40"
                    />
                    <rect
                      x="13"
                      y="20"
                      width="4"
                      height="8"
                      rx="1"
                      fill="#C0522A"
                      fillOpacity="0.55"
                    />
                    <rect
                      x="19"
                      y="16"
                      width="4"
                      height="12"
                      rx="1"
                      fill="#C0522A"
                      fillOpacity="0.70"
                    />
                    <rect
                      x="25"
                      y="18"
                      width="3"
                      height="10"
                      rx="1"
                      fill="#C0522A"
                      fillOpacity="0.55"
                    />

                    {/* card sup der — líneas métricas */}
                    <rect
                      x="34"
                      y="6"
                      width="26"
                      height="24"
                      rx="3"
                      fill="#C0522A"
                      fillOpacity="0.42"
                    />
                    <rect
                      x="34"
                      y="6"
                      width="26"
                      height="6"
                      rx="3"
                      fill="#C0522A"
                      fillOpacity="0.65"
                    />
                    <rect
                      x="34"
                      y="9"
                      width="26"
                      height="3"
                      fill="#C0522A"
                      fillOpacity="0.65"
                    />
                    <rect
                      x="37"
                      y="16"
                      width="18"
                      height="3"
                      rx="1.5"
                      fill="#C0522A"
                      fillOpacity="0.70"
                    />
                    <rect
                      x="37"
                      y="21"
                      width="13"
                      height="2.5"
                      rx="1.2"
                      fill="#C0522A"
                      fillOpacity="0.48"
                    />
                    <rect
                      x="37"
                      y="25"
                      width="16"
                      height="2.5"
                      rx="1.2"
                      fill="#C0522A"
                      fillOpacity="0.35"
                    />

                    {/* card inf izq — líneas métricas */}
                    <rect
                      x="4"
                      y="34"
                      width="26"
                      height="24"
                      rx="3"
                      fill="#C0522A"
                      fillOpacity="0.38"
                    />
                    <rect
                      x="4"
                      y="34"
                      width="26"
                      height="6"
                      rx="3"
                      fill="#C0522A"
                      fillOpacity="0.58"
                    />
                    <rect
                      x="4"
                      y="37"
                      width="26"
                      height="3"
                      fill="#C0522A"
                      fillOpacity="0.58"
                    />
                    <rect
                      x="7"
                      y="44"
                      width="18"
                      height="3"
                      rx="1.5"
                      fill="#C0522A"
                      fillOpacity="0.65"
                    />
                    <rect
                      x="7"
                      y="49"
                      width="13"
                      height="2.5"
                      rx="1.2"
                      fill="#C0522A"
                      fillOpacity="0.42"
                    />
                    <rect
                      x="7"
                      y="53"
                      width="16"
                      height="2.5"
                      rx="1.2"
                      fill="#C0522A"
                      fillOpacity="0.30"
                    />

                    {/* card inf der — PASTEL */}
                    <rect
                      x="34"
                      y="34"
                      width="26"
                      height="24"
                      rx="3"
                      fill="#C0522A"
                      fillOpacity="0.42"
                    />
                    <rect
                      x="34"
                      y="34"
                      width="26"
                      height="6"
                      rx="3"
                      fill="#C0522A"
                      fillOpacity="0.62"
                    />
                    <rect
                      x="34"
                      y="37"
                      width="26"
                      height="3"
                      fill="#C0522A"
                      fillOpacity="0.62"
                    />
                    {/* pastel centrado en card inf der */}
                    <circle
                      cx="47"
                      cy="49"
                      r="8"
                      fill="#C0522A"
                      fillOpacity="0.20"
                    />
                    <path
                      d="M47 49 L47 41 A8 8 0 1 1 40 54 Z"
                      fill="#C0522A"
                      fillOpacity="0.68"
                    />
                    <path
                      d="M47 49 L40 54 A8 8 0 0 1 43.5 41.2 Z"
                      fill="#C0522A"
                      fillOpacity="0.35"
                    />
                    <line
                      x1="47"
                      y1="49"
                      x2="47"
                      y2="41"
                      stroke="#FFB347"
                      strokeWidth="0.9"
                      strokeOpacity="0.70"
                    />
                    <line
                      x1="47"
                      y1="49"
                      x2="40"
                      y2="54"
                      stroke="#FFB347"
                      strokeWidth="0.9"
                      strokeOpacity="0.60"
                    />
                    <circle
                      cx="47"
                      cy="49"
                      r="1.5"
                      fill="#FFB347"
                      fillOpacity="0.8"
                    />

                    {/* acento: línea tendencia diagonal */}
                    <path
                      d="M7 56 L20 42 L36 32 L56 14"
                      fill="none"
                      stroke="#FFB347"
                      strokeWidth="2.8"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                    <path
                      d="M7 56 L20 42 L36 32 L56 14"
                      fill="none"
                      stroke="#FFB347"
                      strokeWidth="6"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeOpacity="0.15"
                    />
                    <circle cx="20" cy="42" r="3" fill="#FFB347" />
                    <circle cx="36" cy="32" r="3" fill="#FFB347" />
                    <circle cx="56" cy="14" r="3" fill="#FFB347" />
                    <polygon points="56,14 49,16 51,22" fill="#FFB347" />
                  </svg>
  );
}
